version: '3'

services:
  api-exceland:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-exceland
    environment:
      - DB_HOST=pg-exceland
      - REDIS_HOST=redis-exceland
    volumes:
      - ./:/usr/server/
    depends_on:
      - pg-exceland
      - redis-exceland
    ports:
      - 0.0.0.0:80:8001
    restart: always

  pg-exceland:
    image: postgres:16.1-alpine3.19
    container_name: pg-exceland
    environment:
      - POSTGRES_USER=marcus
      - POSTGRES_PASSWORD=marcus
      - POSTGRES_DB=exceland
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
      - ./database/structure.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/data.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - 127.0.0.1:5433:5432
    restart: always

  redis-exceland:
    image: redis:7-alpine
    container_name: redis-exceland
    ports:
      - 127.0.0.1:6379:6379
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 0.0.0.0:5050:80
    volumes:
      - ./exceland.backup:/pgadmin4/exceland.backup
    depends_on:
      - pg-exceland
    restart: always

networks:
  default:
    name: api-exceland-network
