services:
  next-auth:
    working_dir: /app
    command: sh -c "npm ci && npm run dev"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ../auth-next:/app
      - next_node_modules:/app/node_modules
      - next_next:/app/.next
    ports:
      - 3000:3000

volumes:
  next_node_modules:
  next_next: