services:
  api-auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-auth
    environment:
      - DB_HOST=pg-auth
      - REDIS_HOST=redis-auth
    volumes:
      - ./:/usr/server/
    depends_on:
      - pg-auth
      - redis-auth
    restart: always

  next-auth:
    build:
      context: ../auth-next
      dockerfile: Dockerfile
    container_name: next-auth
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-auth
    depends_on:
      - api-auth
      - next-auth
    ports:
      - 0.0.0.0:8080:80
      - 0.0.0.0:8443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs
      - certbot-www:/var/www/certbot
      - certbot-conf:/etc/letsencrypt
    restart: always

  pg-auth:
    image: postgres:16.1-alpine3.19
    container_name: pg-auth
    environment:
      - POSTGRES_USER=marcus
      - POSTGRES_PASSWORD=marcus
      - POSTGRES_DB=auth
    volumes:
      - ./data/postgres/:/var/lib/postgresql/data
      - ./database/structure.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/data.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - 127.0.0.1:5433:5432
    restart: always

  redis-auth:
    image: redis:7-alpine
    container_name: redis-auth
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 0.0.0.0:5050:80
    volumes:
      - ./auth.backup:/pgadmin4/auth.backup
    depends_on:
      - pg-auth
    restart: always

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot-www:/var/www/certbot
      - certbot-conf:/etc/letsencrypt
    entrypoint: sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done"

networks:
  default:
    name: my-network
volumes:
  certbot-www:
  certbot-conf:
